### ISSUE TITLE
Support implicit namespace packages

### ISSUE THREAD

**Issue by frostming** [pfmoore/editables#9]
How should editables be used with namespace packages?

```
namespace
    package_a
        __init__.py
    package_b
        __init__.py
```

It seems it cannot be mapped via `EditableProject.map()`

**Comment by frostming** [comment]
Do you suggest falling back to `add_to_path()`(.pth file) in this case?

**Comment by pfmoore** [comment]
Yes, `add_to_path` is the correct way. `map` doesn't work because of the way namespace packages are required to work (the behaviour of dynamically picking up any newly-added content isn't compatible with a simple import hook).

This is mentioned briefly in the README:

> Using `add_to_path` is the only reliable way of supporting implicit namespace packages - the mechanism used in map does not handle them correctly.

Proper docs coming sometime, I promise! 🙂

**Comment by frostming** [comment]
Thanks for the answer, my bad I didn't read the README through.
